Integration n+1
ngeelani48/Blogg-app pull request #8
Opened 2023-06-20 21:10 UTC by ngeelani48

**In this PR @ngeelani48  and @Koshao-sys  fulfilled the following requirements:**

- Solved N+1 problem when fetching all posts and their comments for a user without using the bullet gem.

**Screenshot before**
![Screenshot (99)](https://github.com/ngeelani48/Blogg-app/assets/117263981/a10c778c-f37c-4db8-8138-8edd9dbb1080)

**Screenshot after**
![Screenshot (102)](https://github.com/ngeelani48/Blogg-app/assets/117263981/2e9ffe59-6587-42f4-a585-9610841df2f5)

**Integration specs**

- User index page:
  - I can see the username of all other users.
  - I can see the profile picture for each user.
  - I can see the number of posts each user has written.
  - When I click on a user, I am redirected to that user's show page.
- User show page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see the user's bio.
  - I can see the user's first 3 posts.
  - I can see a button that lets me view a user's posts.
  - When I click a user's post, it redirects me to that post's show page.
  - When I click to see all posts, it redirects me to the user's post's index page.
- User post index page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see a post's title.
  - I can see some of the post's body.
  - I can see the first comments on a post.
  - I can see how many comments a post has.
  - I can see how many likes a post has.
  - I can see a section for pagination if there are more posts than fit on the view.
  - When I click on a post, it redirects me to that post's show page.
- Post-show page:
  - I can see the post's title.
  - I can see who wrote the post.
  - I can see how many comments it has.
  - I can see how many likes it has.
  - I can see the post body.
  - I can see the username of each commenter.
  - I can see the comment each commenter left.

2023-06-20 22:16 UTC, Whoistolu requested changes
Hi @ngeelani48 and @Koshao-sys ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

### N/A

Cheers, and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 22:16 UTC, Whoistolu commented on spec/integration/user_show_spec.rb
> +end
- [ ] [REQUIRED] Kindly add tests that assert you can see a button that lets me view all of a user's posts as stated by the project requirements.

2023-06-20 22:16 UTC, Whoistolu commented on spec/integration/post_index_spec.rb
> +  end
- [ ] [REQUIRED] Kindly add tests that assert you can see a section for pagination if there are more posts than fit on the view as stated in the project requirements.

2023-06-21 05:29 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi team,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-21 07:04 UTC, merged

2023-06-21 15:18 UTC, ngeelani48 commented on spec/integration/post_index_spec.rb
> +  end
@Whoistolu Thanks for the review and your time. I missed some of these tests.